exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: NUWIT
description: "Northeastern University Women in Tech"
email: nuwomenintech@gmail.com
url: "https://nuwit.ccs.neu.edu" # the base hostname & protocol for your site
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
